export const USER_CONNECTED = 'USER_CONNECTED';
export const USER_LIST_UPDATED = 'USER_LIST_UPDATED';
export const INPUT_UPDATED = 'INPUT_UPDATED';
export const USER_SENT_MESSAGE = 'USER_SENT_MESSAGE';
export const USER_RECEIVED_MESSAGE = 'USER_RECEIVED_MESSAGE';
